### ISSUE TITLE
[SAMSUNG] Reporting

### ISSUE THREAD

**Issue by joehand** [datproject/organization#2]
Tracking milestones and other deliverables to report for [Samsung 2018 grant](https://github.com/datproject/organization/tree/master/grants/2018-SamsungNEXT). Expenses for this grant will be tracked via [Open Collective](https://opencollective.com/hyper-star-samsung-next-decentralization-grant/expenses/new).

**Comment by joehand** [comment]
@andrewosh it'd be great to have a little writeup (see MOSS reports for example) of what was achieved with the Samsung Next grant. This helps us get other grants in the future.

**Comment by okdistribute** [comment]
good idea @joehand! ICYMI [moss reports](https://github.com/datproject/organization/pull/8)

**Comment by okdistribute** [comment]
Grant complete! @andrewosh if you have time to write a blog post about how the year went, that would be rad!
