### ISSUE TITLE
[EVENT] Berlin-related events around DTN

### ISSUE THREAD

**Issue by joehand** [datproject/organization#4]
Organizing stuff around DTN in Berlin https://github.com/dat-land/comm-comm/issues/42. 

TODO: 

- [x] public event
  - [x] talk proposals
  - [ ] finalize schedules
- [x] Dat Protocol Moving
- [ ] path to joining decision-making process and leadership meetings

**Comment by okdistribute** [comment]
## Public event at Trust in Berlin, May 19th

If you'd like to give a lightning talk (5 minutes) or a longer talk (20min) or a workshop/discussion (45min+), please post here with:

* talk title and optional short description 
* your name

I'd like to limit longer talks to folks who are working on core ecosystem pieces, although it could be ok if the proposed talk is very relevant to core development.

Talks will be discussed and put on a website by **Friday, May 3rd** 

Thanks for wanting to spur conversation amongst dat developers and show off your work!

**Comment by pfrazee** [comment]
Title: The Unwalled.Garden protocol
Description: How Beaker uses dat for identity, social applications, and content publishing.

**Comment by RangerMauve** [comment]
Title: Dat with multiplayer 3D scenes
Length: 15min?
Description: a quick introduction to how you can build and distribute a 3D scene with Dat, and how you can use Dat's networking layer for decentralized multiplayer.

I think it'd be good to have a quicker talk showing an A-frame scene and publishing it on that also just a quick overview of how the networking would work for the multiplayer. then I can invite people to come over after if they wanted to hack on something like this more

**Comment by okdistribute** [comment]
@mafintosh will give a quick state of Dat (15-20min)

**Comment by karissa** [comment]
@karissa will give a quick talk (10min) about funding progress, finances, and upcoming events

**Comment by joehand** [comment]
Talk about CLI and dat-node things (10 min)

**Comment by heapwolf** [comment]
Title: Learn DAT by implementing it!
Description: Interesting stuff I have learned while implementing hyper-core and the modules it's built on.

**Comment by okdistribute** [comment]
Website now up at events.datproject.org
